#!/bin/bash

# Define the action to take when the SIGTERM signal is caught
trap 'echo "I am invincible!!!"' SIGTERM

# Run the infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
